# constants.py

TAP_THRESHOLD = 0.4
VIEWPORT_SCAN_RANGE = 50
AUTO_CLICK_RETRY_DELAY = 500
MAX_CLICK_RETRIES = 2

MAX_LOAD_MORE_ATTEMPTS = 100
MAX_NO_GROWTH_ATTEMPTS = 5
LOAD_MORE_TIMEOUT_MS = 800
SCAN_PARAGRAPHS_PER_CHUNK = 50
MAX_SCAN_PARAGRAPHS_TOTAL = 8000
PAGE_DOWN_BATCH_SIZE = 3
SORT_PARAGRAPHS_PER_CHUNK = 200
MAX_SORT_ITERATIONS = 2000
MAX_COMBOBOX_RESUME_ATTEMPTS = 20
FOCUS_RECOVERY_WINDOW_SEC = 20
